### PR TITLE
Update to Swift 3

### PR DESCRIPTION
**Pull request by chrisfsampaio**

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
Ah, so someone actually uses this library!

Will look at this tonight.

best case scenario, I'll make a Swift 3 branch, instead of doing a full merge.

**Comment by chrisfsampaio** [comment]
Hahah, yes, there are people using it 😄 
Cool, let me know if you want me to recreate the PR against another branch 👍

**Comment by ArtSabintsev** [comment]
Will do - just got home, so will do this tomorrow afternoon as it's late.

**Comment by ArtSabintsev** [comment]
Done: https://github.com/ArtSabintsev/Magic/pull/8

Now I need to figure out how to add a subspec to the master repo that points to the swift3 branch.

I'm not going to pill in that PR until Swift 3 is live.

**Comment by ArtSabintsev** [comment]
Closing this PR.

**Pull request closed without merging**
